# Generated by Django 3.0.8 on 2020-07-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='query_students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='user name')),
                ('email', models.EmailField(max_length=256, verbose_name='user email')),
                ('phone', models.CharField(max_length=10, verbose_name='user email')),
                ('coaching', models.CharField(max_length=80, verbose_name='user email')),
            ],
        ),
    ]
